[package]
name = "scx_layered"
version = "1.0.2"
authors = ["Tejun Heo <htejun@meta.com>", "Meta"]
edition = "2021"
description = "A highly configurable multi-layer BPF / user space hybrid scheduler used within sched_ext, which is a Linux kernel feature which enables implementing kernel thread schedulers in BPF and dynamically loading them. https://github.com/sched-ext/scx/tree/main"
license = "GPL-2.0-only"

[dependencies]
anyhow = "1.0.65"
bitvec = "1.0"
clap = { version = "4.1", features = ["derive", "env", "unicode", "wrap_help"] }
ctrlc = { version = "3.1", features = ["termination"] }
fb_procfs = "0.7"
lazy_static = "1.4"
libbpf-rs = "0.24.1"
libc = "0.2.137"
log = "0.4.17"
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.12"
metrics = "0.23.0"
metrics-util = "0.17.0"
metrics-exporter-prometheus = "0.15.3"

[build-dependencies]
scx_utils = { path = "../../../rust/scx_utils", version = "1.0.2" }

[features]
enable_backtrace = []
